default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DB_PORT_5432_TCP_ADDR'] || "localhost" %>
  port: <%= ENV['DB_PORT_5432_TCP_PORT'] || 5432 %>
  username: <%= ENV['DBUSER'] || "postgres" %>
  password: <%= ENV['DBPASS'] || "" %>

development:
  <<: *default
  database: <%= ENV['DBNAME'] || "mike_dev" %>

test:
  <<: *default
  database: mike_test

production:
  <<: *default
  database: <%= ENV['DBNAME'] || "mike_prod" %>