default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: kris
  password:

development:
  <<: *default
  database: mike_dev

test:
  <<: *default
  database: mike_test

production:
  <<: *default
  database: mike_prod
